DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS warehouses;
DROP TABLE IF EXISTS warehouse_details;
DROP TABLE IF EXISTS transfers;

CREATE TABLE products(
  pid TEXT PRIMARY KEY,
  pname TEXT NOT NULL,
  pqty TEXT NOT NULL
);

CREATE TABLE warehouses(
  wid TEXT PRIMARY KEY,
  wname TEXT NOT NULL,
  wloc TEXT NOT NULL
);

CREATE TABLE warehouse_details(
  wdid INTEGER PRIMARY KEY,
  wid TEXT,
  pid TEXT,
  pqty INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY(wid) REFERENCES warehouses(wid),
  FOREIGN KEY(pid) REFERENCES products(pid)
);

CREATE TABLE transfers(
  tid INTEGER PRIMARY KEY,
  tfrom INTEGER,
  tto INTEGER,
  pid TEXT NOT NULL,
  tqty INTEGER NOT NULL,
  timestmp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);